### ISSUE TITLE
Failed to install the theme in vue-storefront

### ISSUE THREAD

**Issue by michhy** [AbsoluteWebServices/vuetique-theme#30]
Hello, I have followed the steps on readme to install (i have installed magento2.3 and vue-storefront on my localhost, working fine) , but failed to compile.

I have changed theme in local.json, of course. 
When i try to 'npm run dev' in 'vue-storefront' directory in terminal, 
it shows the following after a while of compiling:

`Entrypoint app = manifest.js vendor.js app.js app.9a182efb56c425306cc7.hot-update.js
[0] multi webpack-hot-middleware/client babel-polyfill ./core/client-entry.ts 52 bytes {app}
[./core/app.ts] 4.77 KiB {app} [1 error]
[./core/build/config.json] 11.9 KiB {app}
[./core/client-entry.ts] 16.5 KiB {app}
[./core/compatibility/plugins/event-bus/index.js] 2.93 KiB {app}
[./core/i18n/index.ts] 1.49 KiB {app}
[./core/lib/async-data-loader.ts] 1.28 KiB {app}
[./core/lib/logger.ts] 6.42 KiB {app}
[./core/lib/multistore.ts] 3.34 KiB {app}
[./core/lib/sync/task.ts] 10.1 KiB {app}
[./core/modules/offline-order/helpers/onNetworkStatusChange.ts] 1.75 KiB {app}
[./core/service-worker/registration.js] 830 bytes {app}
[./core/store/index.ts] 1010 bytes {app}
[./node_modules/babel-polyfill/lib/index.js] 833 bytes {app}
[./node_modules/webpack-hot-middleware/client.js] (webpack)-hot-middleware/client.js 7.59 KiB {app}
    + 1688 hidden modules

WARNING in ./core/app.ts 91:52-62
"export 'themeEntry' was not found in 'theme/index.js'
 @ ./core/client-entry.ts
 @ multi webpack-hot-middleware/client babel-polyfill ./core/client-entry.ts

ERROR in /Users/potehamu/WEB/vue-storefront/core/app.ts
./core/app.ts
[tsl] ERROR in /Users/potehamu/WEB/vue-storefront/core/app.ts(22,10)
      TS2305: Module '"../../../../../Users/potehamu/WEB/vue-storefront/src/themes/vuetique"' has no exported member 'themeEntry'.
Child html-webpack-plugin for "index.amp.html":
`
is there anything I missed in the installing steps?
Thanks in advance.

**Comment by dmitry-kozachek** [comment]
Hi @michhy, please pull latest changes and try again.

**Comment by michhy** [comment]
Hello, thank you.
I have pulled the latest and installed, it has no problem when compile,
but the end result like this : (seems not linking any CSS)

https://ibb.co/fGW9dL9
https://ibb.co/KFrBZRq

thanks again

**Comment by dmitry-kozachek** [comment]
Hello again @michhy,
Did you install tailwindcss? It won't work without that.
https://github.com/AbsoluteWebServices/vuetique-theme#tailwind-prerequisites

**Comment by michhy** [comment]
Oops yes, sorry, I forgot to put that.
It is working like breeze now, thanks a lot!
