### ISSUE TITLE
themes competibility with Vue Storefront 1.9.0-rc.2

### ISSUE THREAD

**Issue by kipotlea** [AbsoluteWebServices/vuetique-theme#31]
I'm trying to install vuetique theme on Vue storefront 1.9.0-rc.2.
But, my theme not changed with vuetique. 

I already follow the instructions and restart the vue-strofront.

**Comment by youanden** [comment]
Hello @kipotlea , we haven't tested with Vue Storefront 1.9.0-rc.2.

If you'd like to use our theme today it'd be best to use the stable release of 1.8.3, or wait for 1.9.0 to be come stable so that we can adjust our theme's compatibility.

**Comment by kipotlea** [comment]
Thanks @youanden
