### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by KevinGorjan** [AbsoluteWebServices/vuetique-theme#40]
Hello

Can you guys update the docs on which versions this theme works?
I'm using Vue StoreFront 1.9.2, but it seems I can't it up and running.

Because Vue StoreFront is now on 1.10.2 and I like to know if you guys keep this theme up-to-date?

Thanks

**Comment by dmitry-kozachek** [comment]
Hi @KevinGorjan,
Added in 7329f78b4103da8b3d613e14bc7dd832db97f352

**Comment by KevinGorjan** [comment]
Thanks!
