### ISSUE TITLE
Error on opening Login Modal

### ISSUE THREAD

**Issue by razzul** [AbsoluteWebServices/vuetique-theme#41]
<div class="text-center p-3">
          <span class="border-wrap"><img src="/razzul/img/blob/master/login-modal.gif?raw=true" alt="login-modal.gif"></span>
      </div>

For Newsletter there is no error but for login modal its getting error

**Comment by dmitry-kozachek** [comment]
Hi @razzul,
Fixed in e50d51a19d766d0850469f377c58c4d630fcdce9
