### ISSUE TITLE
Error while adding product in cart

### ISSUE THREAD

**Issue by razzul** [AbsoluteWebServices/vuetique-theme#43]
<div class="text-center p-3">
          <span class="border-wrap"><img src="/razzul/img/blob/master/add-to-cart-error.gif?raw=true" alt="add-to-cart-error.gif"></span>
      </div>

there is a error regarding notification

**Comment by dmitry-kozachek** [comment]
Hi @razzul,
Fixed in e50d51a19d766d0850469f377c58c4d630fcdce9
