### ISSUE TITLE
  TypeError: Invalid Version: 1.3 when running yarn

### ISSUE THREAD

**Issue by rizwan-i-khan** [AbsoluteWebServices/vuetique-theme#44]
I am trying to install the theme and when I hit yarn in vuetique directory I got below error.

> [Arguments: 
>   /usr/local/bin/node /usr/local/bin/yarn
> 
> PATH: 
>   /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
> 
> Yarn version: 
>   1.19.0
> 
> Node version: 
>   10.16.3
> 
> Platform: 
>   linux x64
> 
> Trace: 
>   TypeError: Invalid Version: 1.3
>       at new SemVer (/usr/local/lib/node_modules/yarn/lib/cli.js:3479:11)
>       at Range.module.exports.Range.test (/usr/local/lib/node_modules/yarn/lib/cli.js:4286:15)
>       at Function.satisfies (/usr/local/lib/node_modules/yarn/lib/cli.js:4335:16)
>       at WorkspaceLayout.getManifestByPattern (/usr/local/lib/node_modules/yarn/lib/cli.js:32262:31)
>       at Function.isWorkspace (/usr/local/lib/node_modules/yarn/lib/cli.js:98062:51)
>       at PackageRequest.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:36629:76)
>       at Generator.next (<anonymous>)
>       at step (/usr/local/lib/node_modules/yarn/lib/cli.js:304:30)
>       at /usr/local/lib/node_modules/yarn/lib/cli.js:322:14
>       at new Promise (<anonymous>)](url)

**Comment by dmitry-kozachek** [comment]
Hi @rizwan-i-khan,
I've fixed theme version.
BTW, you don't need to run yarn from theme folder, just run it from vue-storefront root.

**Comment by rizwan-i-khan** [comment]
HI, @dmitry-kozachek I have run yarn from the vue-storefront root and version error is resolved after your latest commit. but I got this error when `yarn build` can you please help me.
The current yarn version is 1.19.1

> ERROR in ./src/themes/vuetique/index.js
> Module not found: Error: Can't resolve '@vue-storefront/core/lib/router-manager' in '/var/www/html/magento231-vue-pwa/vue-storefront/src/themes/vuetique'
>  @ ./src/themes/vuetique/index.js 7:0-72 24:2-15
>  @ ./core/app.ts
>  @ ./core/client-entry.ts
>  @ multi babel-polyfill ./core/client-entry.ts
