### ISSUE TITLE
My Direct links are not working 

### ISSUE THREAD

**Issue by rebinti** [AbsoluteWebServices/vuetique-theme#45]
Hi I setup vuestorefront using magento1.9. one issue is there. here menu click is not working but if loaded in new tab it's working as expected
any idea the issue was? here I am using Vuetique theme
menu click redirect to same home page.. no actions

**Comment by dmitry-kozachek** [comment]
@rebinti Sorry for the delayed answer. If you still interested in this question it would be great if you add more info like VSF info (version? is it clean istallation?) console output when clicking on menu, api console output
