### ISSUE TITLE
Payment method remains with default 'cashondelivery' after selecting different payment method

### ISSUE THREAD

**Issue by daksamit** [AbsoluteWebServices/vuetique-theme#46]
When we change payment method in checkout, `changePaymentMethod', always returns cashondelivery.
This issue prevents adding custom payment module using event:
```
Vue.prototype.$bus.$on('checkout-payment-method-changed', (paymentMethodCode) => {
  // paymentMethodCode === 'cashondelivery'
})
```

**Comment by dmitry-kozachek** [comment]
@daksamit Sorry for the delayed answer. Could you please check it again with the latest version?

**Comment by daksamit** [comment]
Sorry, currently I'm not working on any vsf related project.

**Comment by dmitry-kozachek** [comment]
Got it, closing
