### ISSUE TITLE
Inproper checkout steps behavior, skips first second step and can't copy shipping data

### ISSUE THREAD

**Issue by daksamit** [AbsoluteWebServices/vuetique-theme#47]
When we enter full name and click CONTINUE TO SHIPPING, it sometimes goes to Payment (3) step instead. 
![image](https://user-images.githubusercontent.com/7165997/68085561-76722700-fe42-11e9-8af1-685e183b5667.png)
Further more, Copy address data from shipping isn't working.
![image](https://user-images.githubusercontent.com/7165997/68085586-c224d080-fe42-11e9-88d5-d15d71fb2f07.png)

**Comment by dmitry-kozachek** [comment]
@daksamit Sorry for the delayed answer. I'm not facing this issue on my clean VSF installation with the latest version of the theme. If you're interested please check it again with the latest version

**Comment by daksamit** [comment]
Ooh, I forget about this. I've been just playing around with vuetique theme and it was my insights :)

**Comment by dmitry-kozachek** [comment]
Ok, closing then
