### ISSUE TITLE
Demo Offline?

### ISSUE THREAD

**Issue by EarthmanWeb** [AbsoluteWebServices/vuetique-theme#50]
Hi, we are considering using/contributing to this theme for a time-sensitive prototype project

It's not clear if it is current and ready for deployment. 

Additionally, the demo at: https://demo.vuetique.io/ is currently offline

Can you please confirm status of the Demo and this project?

Thanks!
Terrrance

**Comment by dmitry-kozachek** [comment]
Hi, `master` branch is ready for deployment, but it's for VSF 1.11. There is `release/1.12.2` branch for VSF 1.12 but it's not fully tested yet.
Demo is offline currently, @youanden may know more about it.

**Comment by dmitry-kozachek** [comment]
@EarthmanWeb Demo is online
