### ISSUE TITLE
Vue-Storefront 1.12 compatibility

### ISSUE THREAD

**Issue by fhaertig** [AbsoluteWebServices/vuetique-theme#51]
Hi, i've seen the 1.12.2 branch and the changes that were made in august '20 - but what's the actual status now? is it fully tested?

thanks for this awesome project!

**Comment by dmitry-kozachek** [comment]
Hi @fhaertig, It was dev tested, I think it should be okay. Though you need to consider it's not under active development

**Comment by fhaertig** [comment]
thanks for the fast response! That's not a problem, we will use it just as a head start then
